# Generated by Django 6.1 on 2026-09-12 13:48

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import hosting.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True, validators=[django.core.validators.RegexValidator('\\A[0-9a-f]{64}\\Z', 'Enter a lowercase SHA-256 digest.')])),
                ('can_write', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosting_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=80, validators=[django.core.validators.RegexValidator('\\A[a-z0-9]+(?:-[a-z0-9]+)*\\Z', 'Use lowercase letters, numbers, and single hyphens.')])),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('members', 'Signed-in members')], default='private', max_length=10)),
                ('is_archived', models.BooleanField(default=False)),
                ('require_download_verification', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('reader', 'Can download'), ('writer', 'Can upload and download')], default='reader', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='hosting.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosting_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending validation'), ('ready', 'Ready'), ('failed', 'Failed'), ('superseded', 'Replaced; awaiting cleanup')], default='pending', max_length=12)),
                ('storage_key', models.CharField(default=uuid.uuid4, editable=False, max_length=255, unique=True)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('sha256', models.CharField(blank=True, max_length=64, validators=[django.core.validators.RegexValidator('\\A[0-9a-f]{64}\\Z', 'Enter a lowercase SHA-256 digest.')])),
                ('archive_size', models.PositiveBigIntegerField(default=0)),
                ('unpacked_size', models.PositiveBigIntegerField(default=0)),
                ('file_count', models.PositiveIntegerField(default=0)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='hosting.project')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosting_uploads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1024, validators=[hosting.models.validate_project_path])),
                ('size', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('\\A[0-9a-f]{64}\\Z', 'Enter a lowercase SHA-256 digest.')])),
                ('content_type', models.CharField(default='application/octet-stream', max_length=127)),
                ('is_binary', models.BooleanField(default=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='hosting.projectupload')),
            ],
            options={
                'ordering': ['path'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='current_upload',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_project', to='hosting.projectupload'),
        ),
        migrations.CreateModel(
            name='TransferEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('push', 'Upload'), ('clone', 'Download')], max_length=8)),
                ('outcome', models.CharField(choices=[('allowed', 'Allowed'), ('denied', 'Denied'), ('failed', 'Failed')], max_length=8)),
                ('byte_count', models.PositiveBigIntegerField(default=0)),
                ('reason', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_events', to='hosting.project')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosting_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_hash', models.CharField(editable=False, max_length=64, unique=True, validators=[django.core.validators.RegexValidator('\\A[0-9a-f]{64}\\Z', 'Enter a lowercase SHA-256 digest.')])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='hosting.accesstoken')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='hosting.projectupload')),
            ],
        ),
        migrations.CreateModel(
            name='DownloadGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('secret_hash', models.CharField(editable=False, max_length=64, unique=True, validators=[django.core.validators.RegexValidator('\\A[0-9a-f]{64}\\Z', 'Enter a lowercase SHA-256 digest.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_grants', to='hosting.accesstoken')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_grants', to='hosting.projectupload')),
                ('verification', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='download_grant', to='hosting.verificationrequest')),
            ],
        ),
        migrations.AddConstraint(
            model_name='accesstoken',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('created_at'))), name='hosting_token_expiry'),
        ),
        migrations.AddConstraint(
            model_name='projectmembership',
            constraint=models.UniqueConstraint(fields=('project', 'user'), name='hosting_member_unique'),
        ),
        migrations.AddIndex(
            model_name='projectupload',
            index=models.Index(fields=['project', 'status'], name='hosting_upload_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectupload',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'ready'), _negated=True), models.Q(('ready_at__isnull', False), models.Q(('sha256', ''), _negated=True)), _connector='OR'), name='hosting_ready_metadata'),
        ),
        migrations.AddConstraint(
            model_name='projectfile',
            constraint=models.UniqueConstraint(fields=('upload', 'path'), name='hosting_file_path_unique'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('slug'), models.F('owner'), name='hosting_owner_slug_unique'),
        ),
        migrations.AddIndex(
            model_name='transferevent',
            index=models.Index(fields=['user', 'action', 'created_at'], name='hosting_event_usage_idx'),
        ),
        migrations.AddConstraint(
            model_name='verificationrequest',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('created_at'))), name='hosting_verify_expiry'),
        ),
        migrations.AddConstraint(
            model_name='verificationrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'approved'), _negated=True), ('verified_at__isnull', False), _connector='OR'), name='hosting_verify_approved'),
        ),
        migrations.AddConstraint(
            model_name='downloadgrant',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('created_at'))), name='hosting_grant_expiry'),
        ),
    ]
