# Generated by Django 6.1 on 2026-09-12 14:21

from django.db import migrations, models


def share_existing_published_projects(apps, schema_editor):
    Project = apps.get_model("hosting", "Project")
    Project.objects.using(schema_editor.connection.alias).filter(
        current_upload__isnull=False, visibility="private"
    ).update(visibility="members")


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('members', 'Signed-in members')], default='members', max_length=10),
        ),
        migrations.RunPython(share_existing_published_projects, reverse_code=migrations.RunPython.noop),
    ]
