# Generated by Django 6.1 on 2026-08-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
