# Generated by Django 6.1 on 2026-08-31 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
